### ISSUE TITLE
Add the 22 new icons

### ISSUE THREAD

**Issue by jordn** [graywolftech/react-heroicons#1]
Thanks for making the package – I prefer the naming on this one (thought personally, I'd default to Outline, and feel Solid should have the suffix 🙂)

https://github.com/refactoringui/heroicons just added 22 new icons. At some, point could they be added?

**Comment by jsmith** [comment]
No problem :) Initially we had these in another repository but it made sense to make them their own package. I think I agree with adding `Solid` as a suffix and might modify the script! It's particularly weird to have one letter JSX elements like `<X></X>` and I would definitely prefer to use `<XSolid></XSolid>`.

Anyway yes of course let me do that now!

**Comment by jsmith** [comment]
Ok you can current install the `@next` version that has the new icons :) I'm going to test my changes tomorrow before publishing `v1.0.0`!

**Comment by jsmith** [comment]
Just released [`v1.0.0`](https://github.com/graywolftech/react-heroicons/releases/tag/v1.0.0)!
