### ISSUE TITLE
Packaging issues preventing vitest from working 

### ISSUE THREAD

**Issue by panthershark** [graywolftech/react-heroicons#14]
I'm actually using the fork for preact, but this issue seems to be present in this upstream repo (and issues are not enabled on the fork).

The error emitted from `vitest` is `Error: Failed to resolve entry for package "preact-heroicons". The package may have incorrect main/module/exports specified in its package.json.`

This documents fixes for it. I hacked the package.json and got past the initial error so I think this can be fixed. 
https://github.com/sheremet-va/dual-packaging

Before I start working on a PR to fix, I want to clarify that this package should only target esm modules.  Is that correct?  

CC: @ekwoka since I'll want to get this fix merged to the preact version too.

**Comment by ekwoka** [comment]
For my package, I'm only targeting ESM, correct, cjs is fine if adding support is simple.

How are you using it to get this error?

(Also of note, at this point the preact-heroicons has little in common with this original package as almost everything was rewritten, but it was inspired by it)

**Comment by panthershark** [comment]
To get the error, I wrote test using `@testing-library/preact`, `vitest`, and `enzyme`.  The test instantiates a preact component that imports an icon from the heroicons package.

@ekwoka - I would've submitted this to your fork,  but issues are not enabled. Using this library is really helpful and this looks like a configuration issue.  I'm happy to submit an SSCCE and a PR to fix it b/c life is much better with this library than without. :)

Also, if we need to close this and move it to the other repo, lmk.

**Comment by ekwoka** [comment]
Yeah, I'll look into the issues thing.

I'm very curious what is actually causing this issue, since it seems like most of those tools are esm first.

**Comment by panthershark** [comment]
I'll create an SSCCE as soon as I get a minute so we have a test case.

**Comment by panthershark** [comment]
Here is a  small example: 

https://github.com/panthershark/sscce-preact-heroicons-vitest-error

**Comment by panthershark** [comment]
I created a new issue over here.  
https://github.com/ekwoka/preact-heroicons/issues/3

This repo looks like it would benefit from updating the package.json and rollup configurations to match the current spec. The PR is here - https://github.com/ekwoka/preact-heroicons/pull/4
