### ISSUE TITLE
Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by soranoo** [graywolftech/react-heroicons#15]
Hello,
I am new to React and TypeScript. This problem bothers me a lot when I use this plugin. How can I fix it? I appreciate it if someone gave me a helping hand.
![image](https://user-images.githubusercontent.com/46896789/214937339-9f5df6e0-2471-4b8c-8d3b-09110c7dcf3f.png)
Here's my `tsconfig.json`
![image](https://user-images.githubusercontent.com/46896789/214937764-49b0de95-0048-4e6c-9f0e-29d5aef8972e.png)

**Comment by jsmith** [comment]
Hi @soranoo, it looks like whatever build tool you are using isn't properly handling the JSX. Is your repository public?

**Comment by soranoo** [comment]
Please check it out.
https://github.com/soranoo/My-Utilities/tree/main/Test/client_

**Comment by jsmith** [comment]
I checked out and ran your code but I'm not very familiar with create-react-app. I'm sorry this isn't much of an answer but I would recommend using [`vite`](https://vitejs.dev/guide/):

```
npm init vite@latest my-app-name --template react-ts
```

Then, using this new template, our react-heroicons package should work as expected!

**Comment by soranoo** [comment]
Thank you so much, it works.
