### ISSUE TITLE
Component by string

### ISSUE THREAD

**Issue by laszlocph** [graywolftech/react-heroicons#3]
Besides of spelling out the component name like `ArchiveSolid`.

Would it make sense to create a generic component, that takes a string param `ArchiveSolid` and then the component dynamically renders the right icon?

I need to make my icons more configurable..

**Comment by jsmith** [comment]
Hmm the tough thing about this is tree shaking. If we had a lookup for every single icon and someone used that lookup, every single icon would be included in the final build.

How many icons do you need to be configurable? Could your generic component take in the icon component itself rather than the string? Here are a few ideas:
```javascript
// Solution 1
// Create a lookup yourself with all of the icons you need
// This way you don't include all icons (192.5 kB minified)
import * as Icons from "@graywolfai/react-heroicons";

const lookup = {
  AcademicCapOutline: Icons.AcademicCapOutline,
  AcademicCapSolid: Icons.AcademicCapSolid,
  AdjustmentsOutline: Icons.AdjustmentsOutline,
  AdjustmentsSolid: Icons.AdjustmentsSolid,
  AnnotationOutline: Icons.AnnotationOutline,
  AnnotationSolid: Icons.AnnotationSolid,
 ...
};

// Solution 2
// Pass down the icon as a prop
// This is what I do when I a component to work when a generic icon
import * as Icons from "@graywolfai/react-heroicons";

export const GenericComponent = ({ icon }) => {
  // here you have complete control and can pass in whatever props you want
  return <icon />;
}

export const SomeComponent = () => {
 return <GenericComponent icon={Icons.AcademicCapOutline} />
}
```

Does this help?

**Comment by laszlocph** [comment]
Not quite. The configuration happens outside of react, so I have to go from string to rendered icon. I understand the tree shaking issue.

Not sure how font-awesome does it technically, but perhaps worth examining the parallels with it, maybe it yeilds some solution.

**Comment by jsmith** [comment]
Ok you might find this [gist](https://gist.github.com/jsmith/96cccfdef264dfab1bf75e02de704e4e) I made useful? This isn't what font-awesome does but it might work for now :) If you want to make any modifications to the above gist, just let me know. I did look at font awesome quickly but it seems much different than my library and would require a fair amount of work.

**Comment by laszlocph** [comment]
Thank you, this will do it! Pardon for making you write this dumb gist.. I should have come up with it. I'm not strong on JS, and not sure about all my options. Thanks again.

**Comment by jsmith** [comment]
No worries :) Glad it helped!

**Comment by naquiroz** [comment]
[I made a library ](https://github.com/naquiroz/heroicons-lookup) for this based on @jsmith  snippet. Anyone's free to contribute 😄

**Comment by ndri** [comment]
Here's a component I use to show icons by string:

```jsx
import * as icons from "@heroicons/react/24/outline";

const HeroIconOutline = ({ icon, ...props }) => {
  const Icon = icons[icon];
  if (!Icon) return <></>;
  return <Icon aria-hidden="true" {...props} />;
};

export default HeroIconOutline;
```

Usage: 

```jsx
<HeroIconOutline icon="AcademicCapIcon" className="w-6 h-6" />
```
