### ISSUE TITLE
Feature request: Map of icons

### ISSUE THREAD

**Issue by ghost** [graywolftech/react-heroicons#5]
Hi there, 

Perhaps it would be a good idea to make a Dictionary available of all typed icons, this will help when one needs to dynamically add the icons.

e.g.

```ts
interface Dictionary<T> {
  [Key: string]: T;
}
```
and then subsequently:
```ts
const iconMap: Dictionary<(props: React.SVGProps<SVGSVGElement>) => JSX.Element> = {
  AcademicCapOutline: heroIcon.AcademicCapOutline,
  AcademicCapSolid: heroIcon.AcademicCapSolid,
  [....]
}
```

So that people are able to dynamically get these icons using something like the code below:
```ts
const HeroIcon = ({ name, ...restprops }: Props & React.SVGProps<SVGSVGElement>): JSX.Element => {
  const Icon = iconMap[name];
  return <Icon {...restprops} />;
};
```

**Comment by jsmith** [comment]
Hey thanks for this suggestion. Would my solution #2 in this comment https://github.com/graywolftech/react-heroicons/issues/3#issuecomment-723144844 work instead? I actually created this dictionary for the icons which can be found in this [gist](https://gist.github.com/jsmith/96cccfdef264dfab1bf75e02de704e4e)

**Comment by ghost** [comment]
Thanks @jsmith, I ended up with the exact same solution myself before you provided the gist. I do understand the issues with tree-shaking (and this is something I hadn't thought about) so that's at least some added insight. Thank you.

**Comment by jsmith** [comment]
Ok great :) The tree-shaking aspect isn't a *huge* issue since the icons are only like 29.1 kB when they are minified + gzipped. Anyway, glad I could help!

**Comment by naquiroz** [comment]
[I made a library ](https://github.com/naquiroz/heroicons-lookup) for this based on @jsmith  snippet. Anyone's free to contribute 😄
