### ISSUE TITLE
Icons try and use `import`, but package isn't an ESM module

### ISSUE THREAD

**Issue by mikemaccana** [graywolftech/react-heroicons#7]
Heya! Small error in `@graywolfai/react-heroicons@1.2.3` produced by using `import` outside an ESM module:.

We have some unit tests in jest (including UI / DOM tests) and this causes the error below:

```
/app/frontend/node_modules/@graywolfai/react-heroicons/dist/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import React from 'react';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

Right now we're working around this by adding a transform just for this package. I'm not entirely sure what the best solution is (`.mjs`, `type: 'module'` or something else) but just an FYI.

Thanks for the lovely icons!

**Comment by jsmith** [comment]
Hmm let me check tomorrow, thanks for the bug report!

**Comment by jsmith** [comment]
Before I try anything, if you set `"type": "module"` to `node_modules/@graywolfai/package.json`, does that fix the problem?

Edit: If your code is public, I could test of the bug myself. Lmk!

**Comment by jsmith** [comment]
Hey @mikemaccana, just wondering if this is still an issue?
